version: 0.1.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  verbosity: minimal
  publish_nuget: true
  project: Inliner.sln

before_build:
- nuget restore

artifacts:
  - path: '*.nupkg' # find all NuGet packages recursively

test:
  categories:
    except:
    - Integration
    
